### How The Current Flow Works

1. **Interception:** When a request hits the controller, Spring intercepts the payload before it enters your method because of the `@Valid` annotation.
2. **Evaluation:** Spring runs the payload through the Hibernate Validator. It checks all standard annotations (like `@NotNull`) and triggers your custom `SearchRequestValidator` for `@ValidSearchRequest`.
3. **Exception Generation:** If any constraints fail, Spring aborts the request and throws a `MethodArgumentNotValidException` (or `ConstraintViolationException`). Crucially, this exception contains a `BindingResult` object, which holds a detailed list of every specific field that failed and why.
4. **Exception Handling:** Your `GlobalExceptionHandler` catches this exception and translates it into an `ErrorResponse`.

**The Root Cause:** Your `GlobalExceptionHandler` is likely catching the exception but ignoring the detailed `BindingResult` payload inside it. It is simply returning a hardcoded "Validation failure" string to the frontend, swallowing the useful backend errors.

---

### How to Improve the Validation Messages

To fix this, you need to extract the detailed field errors in your exception handler and pass them down to the frontend in a structured way.

#### 1. Update your `ErrorResponse` structure

Ensure your JSON response can hold a list of specific field errors so the frontend knows exactly which inputs to highlight.

```java
public class ErrorResponse {
    private String message;
    private List<FieldErrorDetails> errors; // Add this

    // standard getters/setters
}

public class FieldErrorDetails {
    private String field;
    private String reason;
    // constructors, getters, setters
}

```

#### 2. Update the `GlobalExceptionHandler`

Modify the handler to loop through the `BindingResult` and extract the specific field errors generated by your annotations.

```java
@ExceptionHandler(MethodArgumentNotValidException.class)
@ResponseStatus(HttpStatus.BAD_REQUEST)
public ErrorResponse handleValidationExceptions(MethodArgumentNotValidException ex) {
    List<FieldErrorDetails> details = new ArrayList<>();
    
    // Extract the exact field errors from the exception
    for (FieldError error : ex.getBindingResult().getFieldErrors()) {
        details.add(new FieldErrorDetails(error.getField(), error.getDefaultMessage()));
    }

    ErrorResponse response = new ErrorResponse();
    response.setMessage("Validation failure"); // Keep the generic top-level message
    response.setErrors(details); // Attach the detailed reasons

    return response;
}

```

#### 3. Make Bean Annotations Descriptive

Instead of relying on the default framework messages, specify exactly what the user did wrong directly in the annotations.

```java
public class SearchRequest {
    @NotBlank(message = "Search query cannot be empty")
    private String query;

    @Min(value = 1, message = "Page number must be greater than 0")
    private int page;
}

```

#### 4. Map Custom Validation to Specific Fields

In your custom `SearchRequestValidator`, if a specific filter is missing a field, don't throw a generic class-level error. Bind the error to the specific field path so the frontend can display it next to the relevant input.

```java
public class SearchRequestValidator implements ConstraintValidator<ValidSearchRequest, SearchRequest> {
    
    @Override
    public boolean isValid(SearchRequest request, ConstraintValidatorContext context) {
        if (request.getFilter() != null && request.getFilter().getStartDate() == null) {
            
            // 1. Disable the default class-level error
            context.disableDefaultConstraintViolation();
            
            // 2. Attach the error to the specific field (e.g., "filter.startDate")
            context.buildConstraintViolationWithTemplate("Start date is required when using filters")
                   .addPropertyNode("filter")
                   .addPropertyNode("startDate")
                   .addConstraintViolation();
            
            return false;
        }
        return true;
    }
}

```
